### ISSUE TITLE
EPS files false-positive

### ISSUE THREAD

**Issue by jonpas** [arma-actions/bom-check#1]
Example file: https://github.com/acemod/ACEX/blob/master/extras/assets/logo/black/ACEX-Logo.eps

File is marked as BOM even though it does not actually contain one.

**Comment by veteran29** [comment]
![image](https://user-images.githubusercontent.com/4293906/75777026-7aad4300-5d55-11ea-84b6-7ac949f96581.png)

Does look like BOM to me. Maybe I could change it so it only checks first line 🤔

**Comment by jonpas** [comment]
Yeah, I thought it was. I believe BOM is only used by editors if at the beginning of a file, so your solution would work.

**Comment by veteran29** [comment]
I've changed the check to check only beggining of the lines. No time to switch it into first line only now.

Also I've created v1 tag which will always point to latest release from v1.x branch
